# http://www.appveyor.com/docs/appveyor-yml

# Set build version format here instead of in the admin panel
version: '{build}'

# branches to build
branches:
  # whitelist
  only:
    - master
    - production

  # blacklist
  except:
    - gh-pages

# Do not build on gh tags
skip_tags: true

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# Test against these versions of Node.js
environment:
  matrix:
    # Node versions to run
    - nodejs_version: '10.0.0'

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

# Install scripts--runs after repo cloning
install:
# Install the latest stable version of Node
  - ps: Install-Product node $env:nodejs_version
  - npm install

# Disable automatic builds
build: 'off'

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run test and build
  - npm run deploy

# Cache node_modules for faster builds
cache:
 - "%LOCALAPPDATA%\\Yarn"
 - node_modules -> package.json

artifacts:
  - path: '*.zip'
    name: barthachijuu-io

deploy:
  - provider: FTP
    name: production
    on:
      branch: master
    protocol: ftp
    host: ftp.cluster028.hosting.ovh.net
    username: barthag
    password:
      secure: W1zBAdWLOOWBGhbRmO00vQ==
    folder: www
    debug: true # show complete FTP log
